import type {
  User,
  Department,
  Major,
  Class,
  Course,
  Schedule,
  Role,
  Notification,
  DashboardSummary,
  RegistrationChartData,
  MajorDistribution,
  AttendanceByMonth,
  RecentActivity,
} from "@/types";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "u_1",
    firstName: "Sophea",
    lastName: "Chan",
    email: "sophea.chan@example.edu",
    phone: "+855-12-345-678",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophea",
    roles: ["Admin"],
    department: "Administration",
    departmentId: "dept_1",
    status: "active",
    lastLogin: "2025-10-24T08:45:00Z",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2025-10-24T08:45:00Z",
  },
  {
    id: "u_2",
    firstName: "Dara",
    lastName: "Sok",
    email: "dara.sok@example.edu",
    phone: "+855-12-345-679",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dara",
    roles: ["Lecturer"],
    department: "Computer Science",
    departmentId: "dept_2",
    status: "active",
    lastLogin: "2025-10-23T14:20:00Z",
    createdAt: "2024-02-10T00:00:00Z",
    updatedAt: "2025-10-23T14:20:00Z",
  },
  {
    id: "u_3",
    firstName: "Sreymom",
    lastName: "Ly",
    email: "sreymom.ly@example.edu",
    phone: "+855-12-345-680",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sreymom",
    roles: ["Staff"],
    department: "Business Administration",
    departmentId: "dept_3",
    status: "active",
    lastLogin: "2025-10-24T09:15:00Z",
    createdAt: "2024-03-05T00:00:00Z",
    updatedAt: "2025-10-24T09:15:00Z",
  },
];

// Mock Departments
export const mockDepartments: Department[] = [
  {
    id: "dept_1",
    name: "Administration",
    code: "ADM",
    description: "Administrative offices and management",
    headId: "u_1",
    contactEmail: "admin@example.edu",
    contactPhone: "+855-23-123-456",
    majorCount: 0,
    status: "active",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dept_2",
    name: "Computer Science",
    code: "CS",
    description: "Faculty of Computer Science and Information Technology",
    headId: "u_2",
    contactEmail: "cs@example.edu",
    contactPhone: "+855-23-123-457",
    majorCount: 3,
    status: "active",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dept_3",
    name: "Business Administration",
    code: "BA",
    description: "Faculty of Business and Management",
    contactEmail: "business@example.edu",
    contactPhone: "+855-23-123-458",
    majorCount: 2,
    status: "active",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

// Mock Majors
export const mockMajors: Major[] = [
  {
    id: "maj_1",
    name: "Software Engineering",
    code: "SE",
    departmentId: "dept_2",
    department: mockDepartments[1],
    level: "Bachelor",
    description: "Software development, testing, and project management",
    duration: 4,
    requiredCredits: 120,
    accreditation: "ABET",
    activeStudents: 145,
    status: "active",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "maj_2",
    name: "Data Science",
    code: "DS",
    departmentId: "dept_2",
    department: mockDepartments[1],
    level: "Bachelor",
    description: "Data analysis, machine learning, and AI",
    duration: 4,
    requiredCredits: 120,
    activeStudents: 98,
    status: "active",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
];

// Mock Roles
export const mockRoles: Role[] = [
  {
    id: "role_1",
    name: "Admin",
    description: "Full system access",
    permissions: {
      Users: ["Create", "Read", "Update", "Delete", "Export"],
      Departments: ["Create", "Read", "Update", "Delete", "Export"],
      Majors: ["Create", "Read", "Update", "Delete", "Export"],
      Classes: ["Create", "Read", "Update", "Delete", "Export"],
      Courses: ["Create", "Read", "Update", "Delete", "Export"],
      Schedule: ["Create", "Read", "Update", "Delete", "Export"],
      Attendance: ["Create", "Read", "Update", "Delete", "Export"],
      Announcements: ["Create", "Read", "Update", "Delete", "Export"],
    },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "role_2",
    name: "Staff",
    description: "Academic staff with limited permissions",
    permissions: {
      Users: ["Read"],
      Departments: ["Read"],
      Majors: ["Read"],
      Classes: ["Read", "Update"],
      Courses: ["Read"],
      Schedule: ["Read", "Create", "Update"],
      Attendance: ["Read", "Create", "Update"],
      Announcements: ["Read", "Create"],
    },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];

// Mock Dashboard Data
export const mockDashboardSummary: DashboardSummary = {
  totalStudents: 1250,
  totalTeachers: 85,
  activeCourses: 156,
  activeClasses: 42,
};

export const mockRegistrationData: RegistrationChartData[] = [
  { month: "Jan", count: 45 },
  { month: "Feb", count: 52 },
  { month: "Mar", count: 78 },
  { month: "Apr", count: 65 },
  { month: "May", count: 89 },
  { month: "Jun", count: 120 },
  { month: "Jul", count: 145 },
  { month: "Aug", count: 178 },
  { month: "Sep", count: 210 },
  { month: "Oct", count: 198 },
  { month: "Nov", count: 165 },
  { month: "Dec", count: 105 },
];

export const mockMajorDistribution: MajorDistribution[] = [
  { majorName: "Software Engineering", count: 145 },
  { majorName: "Data Science", count: 98 },
  { majorName: "Business Admin", count: 210 },
  { majorName: "Marketing", count: 156 },
  { majorName: "Accounting", count: 189 },
];

export const mockAttendanceByMonth: AttendanceByMonth[] = [
  { month: "Jan", rate: 92 },
  { month: "Feb", rate: 89 },
  { month: "Mar", rate: 94 },
  { month: "Apr", rate: 91 },
  { month: "May", rate: 88 },
  { month: "Jun", rate: 90 },
];

export const mockRecentActivity: RecentActivity[] = [
  {
    id: "act_1",
    type: "user_created",
    description: "New user Dara Sok registered as Lecturer",
    timestamp: "2025-10-24T10:30:00Z",
  },
  {
    id: "act_2",
    type: "class_scheduled",
    description: "Class CS301 scheduled for Monday 9:00 AM",
    timestamp: "2025-10-24T09:15:00Z",
  },
  {
    id: "act_3",
    type: "announcement",
    description: "New announcement posted: Mid-term exam schedule",
    timestamp: "2025-10-23T16:45:00Z",
  },
];

// Mock Staff-specific data
export const mockStaffAttendance: any[] = [
  {
    id: "att_1",
    studentId: "u_3",
    student: mockUsers[2],
    classId: "class_1",
    className: "CS301",
    date: "2025-10-25",
    status: "present",
    checkInTime: "08:30",
    checkOutTime: "16:30",
  },
  {
    id: "att_2",
    studentId: "u_3",
    student: mockUsers[2],
    classId: "class_1",
    className: "CS301",
    date: "2025-10-24",
    status: "late",
    checkInTime: "09:15",
    checkOutTime: "16:45",
    notes: "Traffic delay",
  },
];

export const mockStaffResults: any[] = [
  {
    id: "res_1",
    studentId: "u_3",
    student: mockUsers[2],
    classId: "class_1",
    className: "CS301",
    courseId: "course_1",
    courseName: "Data Structures",
    semester: "1",
    academicYear: "2024-2025",
    midtermScore: 85,
    finalScore: 90,
    totalScore: 87.5,
    grade: "A",
    status: "passed",
    credits: 3,
    gpa: 4.0,
  },
  {
    id: "res_2",
    studentId: "u_3",
    student: mockUsers[2],
    classId: "class_1",
    className: "CS301",
    courseId: "course_2",
    courseName: "Algorithms",
    semester: "1",
    academicYear: "2024-2025",
    midtermScore: 78,
    finalScore: 82,
    totalScore: 80,
    grade: "B+",
    status: "passed",
    credits: 3,
    gpa: 3.5,
  },
];

export const mockStaffCertificates: any[] = [
  {
    id: "cert_1",
    studentId: "u_3",
    student: mockUsers[2],
    type: "graduation",
    title: "Bachelor of Science in Computer Science",
    description: "Graduation certificate for completing the Computer Science program",
    issueDate: "2025-06-15",
    graduationDate: "2025-05-30",
    gpa: 3.8,
    major: "Computer Science",
    status: "issued",
    template: "graduation_template_1",
  },
  {
    id: "cert_2",
    studentId: "u_3",
    student: mockUsers[2],
    type: "completion",
    title: "Course Completion Certificate",
    description: "Certificate for completing Data Structures course",
    issueDate: "2025-01-15",
    status: "issued",
    template: "completion_template_1",
  },
];

export const mockStaffReports: any[] = [
  {
    id: "rep_1",
    title: "Monthly Attendance Report - October 2025",
    type: "attendance",
    description: "Comprehensive attendance report for all classes in October",
    generatedBy: "Dara Sok",
    generatedAt: "2025-10-25T10:00:00Z",
    period: "October 2025",
    status: "completed",
    format: "pdf",
    size: "2.3 MB",
  },
  {
    id: "rep_2",
    title: "Academic Performance Report - Semester 1",
    type: "academic",
    description: "Student academic performance analysis for semester 1",
    generatedBy: "Dara Sok",
    generatedAt: "2025-10-24T15:30:00Z",
    period: "Semester 1 2024-2025",
    status: "completed",
    format: "excel",
    size: "1.8 MB",
  },
];

export const mockStaffAnnouncements: any[] = [
  {
    id: "ann_1",
    title: "Mid-term Examination Schedule",
    content: "The mid-term examinations for Semester 1 will begin on November 15th. Please check your individual schedules.",
    type: "academic",
    priority: "high",
    targetAudience: "students",
    status: "published",
    createdBy: mockUsers[1],
    createdAt: "2025-10-20T09:00:00Z",
    publishedAt: "2025-10-20T10:00:00Z",
    views: 1250,
    recipients: 1200,
  },
  {
    id: "ann_2",
    title: "Campus Maintenance Notice",
    content: "The main library will be closed for maintenance from October 25th to October 27th.",
    type: "administrative",
    priority: "medium",
    targetAudience: "all",
    status: "published",
    createdBy: mockUsers[2],
    createdAt: "2025-10-18T14:30:00Z",
    publishedAt: "2025-10-18T15:00:00Z",
    views: 890,
    recipients: 1450,
  },
];

// Lecturer-specific mock data
export const mockLecturerContracts: any[] = [
  {
    id: "contract_1",
    lecturerId: "u_2",
    lecturer: mockUsers[1],
    contractType: "Full-time",
    position: "Senior Lecturer",
    department: "Computer Science",
    startDate: "2024-08-01",
    endDate: "2027-07-31",
    salary: 45000,
    currency: "USD",
    workingHours: 40,
    status: "active",
    terms: "Standard teaching contract with research responsibilities",
    signedDate: "2024-07-15",
    renewalEligible: true,
    performanceRating: 4.5,
    createdAt: "2024-07-01T00:00:00Z",
    updatedAt: "2024-07-15T00:00:00Z",
  },
  {
    id: "contract_2",
    lecturerId: "u_2",
    lecturer: mockUsers[1],
    contractType: "Part-time",
    position: "Guest Lecturer",
    department: "Computer Science",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    salary: 25000,
    currency: "USD",
    workingHours: 20,
    status: "completed",
    terms: "Guest lecturing for advanced algorithms course",
    signedDate: "2023-12-15",
    renewalEligible: false,
    performanceRating: 4.8,
    createdAt: "2023-12-01T00:00:00Z",
    updatedAt: "2024-12-31T00:00:00Z",
  },
];

export const mockLecturerAttendance: any[] = [
  {
    id: "lec_att_1",
    lecturerId: "u_2",
    lecturer: mockUsers[1],
    date: "2025-10-25",
    checkInTime: "08:15",
    checkOutTime: null,
    status: "checked_in",
    location: "Building A, Room 301",
    notes: "",
    totalHours: null,
    createdAt: "2025-10-25T08:15:00Z",
  },
  {
    id: "lec_att_2",
    lecturerId: "u_2",
    lecturer: mockUsers[1],
    date: "2025-10-24",
    checkInTime: "08:30",
    checkOutTime: "17:00",
    status: "completed",
    location: "Building A, Room 301",
    notes: "",
    totalHours: 8.5,
    createdAt: "2025-10-24T08:30:00Z",
  },
  {
    id: "lec_att_3",
    lecturerId: "u_2",
    lecturer: mockUsers[1],
    date: "2025-10-23",
    checkInTime: "09:15",
    checkOutTime: "16:45",
    status: "completed",
    location: "Building A, Room 301",
    notes: "Late due to traffic",
    totalHours: 7.5,
    createdAt: "2025-10-23T09:15:00Z",
  },
];

export const mockStudentResults = [
  {
    id: "res_1",
    courseCode: "CS301",
    courseName: "Data Structures",
    credits: 3,
    totalScore: 87.5,
    grade: "A",
    gpa: 4.0,
    semester: "1",
    academicYear: "2024-2025",
  },
  {
    id: "res_2",
    courseCode: "CS302",
    courseName: "Algorithms",
    credits: 3,
    totalScore: 82.0,
    grade: "B+",
    gpa: 3.5,
    semester: "1",
    academicYear: "2024-2025",
  },
  {
    id: "res_3",
    courseCode: "CS303",
    courseName: "Database Systems",
    credits: 3,
    totalScore: 90.0,
    grade: "A",
    gpa: 4.0,
    semester: "1",
    academicYear: "2024-2025",
  },
  {
    id: "res_4",
    courseCode: "MATH201",
    courseName: "Discrete Mathematics",
    credits: 3,
    totalScore: 78.5,
    grade: "B+",
    gpa: 3.5,
    semester: "1",
    academicYear: "2024-2025",
  },
  {
    id: "res_5",
    courseCode: "ENG101",
    courseName: "Academic English",
    credits: 2,
    totalScore: 85.0,
    grade: "A",
    gpa: 4.0,
    semester: "1",
    academicYear: "2024-2025",
  },
];

export const mockStudentFeedback = [
  {
    id: "fb_1",
    category: "lecturer",
    subject: "Course Material Suggestions",
    message: "I would like to suggest adding more practical examples in the Data Structures course. The current materials are good but could benefit from more real-world applications.",
    status: "replied",
    reply: "Thank you for your valuable feedback. We will incorporate more practical examples in the upcoming lectures. Your suggestion has been noted for curriculum improvement.",
    createdAt: "2025-10-15T10:30:00Z",
    updatedAt: "2025-10-16T14:20:00Z",
  },
  {
    id: "fb_2",
    category: "facility",
    subject: "Library Study Space",
    message: "The library study spaces are often overcrowded during exam periods. Could we have more study areas or extended hours?",
    status: "pending",
    createdAt: "2025-10-20T16:45:00Z",
    updatedAt: "2025-10-20T16:45:00Z",
  },
  {
    id: "fb_3",
    category: "course",
    subject: "Assignment Deadlines",
    message: "Some assignment deadlines seem too close together. Could we have better spacing between major assignments?",
    status: "replied",
    reply: "We appreciate your concern about assignment scheduling. The department will review the assignment timeline for better distribution. Thank you for bringing this to our attention.",
    createdAt: "2025-10-10T09:15:00Z",
    updatedAt: "2025-10-12T11:30:00Z",
  },
];

export const mockTeachingReports: any[] = [
  {
    id: "report_1",
    lecturerId: "u_2",
    lecturer: mockUsers[1],
    title: "Teaching Performance Report - Semester 1 2024-2025",
    type: "performance",
    period: "2024-2025 Semester 1",
    courses: [
      {
        courseId: "course_1",
        courseName: "Data Structures",
        classCode: "CS301",
        studentsEnrolled: 35,
        averageScore: 82.5,
        attendanceRate: 88,
        studentSatisfaction: 4.2,
      },
      {
        courseId: "course_2",
        courseName: "Algorithms",
        classCode: "CS302",
        studentsEnrolled: 28,
        averageScore: 78.9,
        attendanceRate: 92,
        studentSatisfaction: 4.5,
      },
    ],
    overallMetrics: {
      totalStudents: 63,
      averageScore: 80.7,
      averageAttendance: 90,
      averageSatisfaction: 4.35,
      teachingHours: 120,
      researchPublications: 2,
    },
    status: "completed",
    generatedAt: "2025-01-15T10:00:00Z",
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "report_2",
    lecturerId: "u_2",
    lecturer: mockUsers[1],
    title: "Course Analytics Report - October 2025",
    type: "analytics",
    period: "October 2025",
    courses: [
      {
        courseId: "course_1",
        courseName: "Data Structures",
        classCode: "CS301",
        studentsEnrolled: 35,
        weeklyAttendance: [95, 92, 88, 90],
        assignmentCompletion: 85,
        quizAverage: 78,
        participationScore: 4.1,
      },
    ],
    overallMetrics: {
      totalStudents: 35,
      averageAttendance: 91.25,
      assignmentCompletionRate: 85,
      quizAverage: 78,
      participationScore: 4.1,
    },
    status: "completed",
    generatedAt: "2025-10-25T09:00:00Z",
    createdAt: "2025-10-25T09:00:00Z",
  },
];

export const mockStudentScores: any[] = [
  {
    id: "score_1",
    studentId: "stu_1",
    student: {
      id: "stu_1",
      firstName: "Sokha",
      lastName: "Chen",
      email: "sokha.chen@student.edu",
    },
    courseId: "course_1",
    courseName: "Data Structures",
    classId: "class_1",
    classCode: "CS301",
    semester: "1",
    academicYear: "2024-2025",
    assessments: [
      {
        type: "midterm",
        name: "Mid-term Exam",
        score: 85,
        maxScore: 100,
        weight: 30,
        date: "2025-10-15",
      },
      {
        type: "assignment",
        name: "Assignment 1",
        score: 92,
        maxScore: 100,
        weight: 20,
        date: "2025-09-20",
      },
      {
        type: "assignment",
        name: "Assignment 2",
        score: 88,
        maxScore: 100,
        weight: 20,
        date: "2025-10-05",
      },
      {
        type: "quiz",
        name: "Weekly Quiz",
        score: 78,
        maxScore: 100,
        weight: 15,
        date: "2025-10-20",
      },
      {
        type: "participation",
        name: "Class Participation",
        score: 90,
        maxScore: 100,
        weight: 15,
        date: "2025-10-25",
      },
    ],
    totalScore: 87.5,
    grade: "A",
    status: "graded",
    lecturerId: "u_2",
    lecturer: mockUsers[1],
    gradedAt: "2025-10-25T14:00:00Z",
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2025-10-25T14:00:00Z",
  },
  {
    id: "score_2",
    studentId: "stu_2",
    student: {
      id: "stu_2",
      firstName: "Maly",
      lastName: "Kim",
      email: "maly.kim@student.edu",
    },
    courseId: "course_1",
    courseName: "Data Structures",
    classId: "class_1",
    classCode: "CS301",
    semester: "1",
    academicYear: "2024-2025",
    assessments: [
      {
        type: "midterm",
        name: "Mid-term Exam",
        score: 78,
        maxScore: 100,
        weight: 30,
        date: "2025-10-15",
      },
      {
        type: "assignment",
        name: "Assignment 1",
        score: 85,
        maxScore: 100,
        weight: 20,
        date: "2025-09-20",
      },
      {
        type: "assignment",
        name: "Assignment 2",
        score: 82,
        maxScore: 100,
        weight: 20,
        date: "2025-10-05",
      },
      {
        type: "quiz",
        name: "Weekly Quiz",
        score: 75,
        maxScore: 100,
        weight: 15,
        date: "2025-10-20",
      },
      {
        type: "participation",
        name: "Class Participation",
        score: 85,
        maxScore: 100,
        weight: 15,
        date: "2025-10-25",
      },
    ],
    totalScore: 81.5,
    grade: "B+",
    status: "graded",
    lecturerId: "u_2",
    lecturer: mockUsers[1],
    gradedAt: "2025-10-25T14:00:00Z",
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2025-10-25T14:00:00Z",
  },
];

export const mockLecturerAnnouncements: any[] = [
  {
    id: "lec_ann_1",
    title: "Updated Course Syllabus - Data Structures",
    content: "I've updated the course syllabus with additional topics on advanced data structures. Please review the changes and let me know if you have any questions.",
    type: "academic",
    priority: "medium",
    targetAudience: "students",
    targetClassIds: ["class_1"],
    status: "published",
    createdBy: mockUsers[1],
    createdAt: "2025-10-20T10:00:00Z",
    publishedAt: "2025-10-20T10:30:00Z",
    views: 35,
    recipients: 35,
    attachments: ["syllabus_v2.pdf"],
  },
  {
    id: "lec_ann_2",
    title: "Office Hours Change This Week",
    content: "Due to a conference, my office hours will be changed to Thursday 2-4 PM instead of the usual Monday schedule.",
    type: "administrative",
    priority: "high",
    targetAudience: "students",
    targetClassIds: ["class_1", "class_2"],
    status: "published",
    createdBy: mockUsers[1],
    createdAt: "2025-10-22T08:00:00Z",
    publishedAt: "2025-10-22T08:15:00Z",
    views: 28,
    recipients: 63,
  },
  {
    id: "lec_ann_3",
    title: "Research Opportunity - AI in Education",
    content: "I'm looking for undergraduate students interested in research on AI applications in education. If you're interested, please contact me during office hours.",
    type: "research",
    priority: "low",
    targetAudience: "students",
    targetClassIds: ["class_1", "class_2"],
    status: "published",
    createdBy: mockUsers[1],
    createdAt: "2025-10-18T14:00:00Z",
    publishedAt: "2025-10-18T14:30:00Z",
    views: 45,
    recipients: 63,
  },
];

// Student-specific mock data
export const mockStudentDashboard = {
  attendanceRate: 92,
  gpa: 3.8,
  registeredCourses: 5,
  unreadAnnouncements: 3,
  performanceData: [
    { semester: "Fall 2023", gpa: 3.5 },
    { semester: "Spring 2024", gpa: 3.7 },
    { semester: "Fall 2024", gpa: 3.8 },
  ],
  attendanceData: [
    { name: "Present", value: 92 },
    { name: "Absent", value: 8 },
  ],
};

export const mockStudentAnnouncements = [
  {
    id: "ann_1",
    title: "Mid-term Examination Schedule",
    message: "The mid-term examinations for Semester 1 will begin on November 15th. Please check your individual schedules.",
    type: "academic",
    priority: "high",
    targetAudience: "students",
    status: "published",
    createdAt: "2025-10-20T09:00:00Z",
    publishedAt: "2025-10-20T10:00:00Z",
    views: 1250,
    recipients: 1200,
  },
  {
    id: "ann_2",
    title: "Campus Maintenance Notice",
    message: "The main library will be closed for maintenance from October 25th to October 27th.",
    type: "administrative",
    priority: "medium",
    targetAudience: "all",
    status: "published",
    createdAt: "2025-10-18T14:30:00Z",
    publishedAt: "2025-10-18T15:00:00Z",
    views: 890,
    recipients: 1450,
  },
  {
    id: "ann_3",
    title: "New Course Registration",
    message: "Registration for Spring 2025 courses opens on November 1st. Don't miss out on popular courses!",
    type: "academic",
    priority: "medium",
    targetAudience: "students",
    status: "published",
    createdAt: "2025-10-15T11:00:00Z",
    publishedAt: "2025-10-15T11:30:00Z",
    views: 2100,
    recipients: 1200,
  },
];

export const mockStudentSchedule = [
  {
    id: "sch_1",
    course: {
      id: "course_1",
      code: "CS301",
      title: "Data Structures",
      credits: 3,
    },
    courseId: "course_1",
    class: {
      id: "class_1",
      code: "CS301-A",
      name: "Data Structures A",
    },
    classId: "class_1",
    lecturer: mockUsers[1],
    lecturerId: "u_2",
    room: "Room 301",
    dayOfWeek: "Monday",
    startTime: "09:00",
    endTime: "10:30",
    academicYear: "2024-2025",
    semester: "1",
    createdAt: "2024-08-01T00:00:00Z",
    updatedAt: "2024-08-01T00:00:00Z",
  },
  {
    id: "sch_2",
    course: {
      id: "course_2",
      code: "CS302",
      title: "Algorithms",
      credits: 3,
    },
    courseId: "course_2",
    class: {
      id: "class_2",
      code: "CS302-A",
      name: "Algorithms A",
    },
    classId: "class_2",
    lecturer: mockUsers[1],
    lecturerId: "u_2",
    room: "Room 302",
    dayOfWeek: "Tuesday",
    startTime: "14:00",
    endTime: "15:30",
    academicYear: "2024-2025",
    semester: "1",
    createdAt: "2024-08-01T00:00:00Z",
    updatedAt: "2024-08-01T00:00:00Z",
  },
  {
    id: "sch_3",
    course: {
      id: "course_3",
      code: "CS303",
      title: "Database Systems",
      credits: 3,
    },
    courseId: "course_3",
    class: {
      id: "class_3",
      code: "CS303-A",
      name: "Database Systems A",
    },
    classId: "class_3",
    lecturer: mockUsers[1],
    lecturerId: "u_2",
    room: "Room 303",
    dayOfWeek: "Wednesday",
    startTime: "10:00",
    endTime: "11:30",
    academicYear: "2024-2025",
    semester: "1",
    createdAt: "2024-08-01T00:00:00Z",
    updatedAt: "2024-08-01T00:00:00Z",
  },
];

export const mockStudentProfile = {
  studentId: "ST123456",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Student",
  personalInfo: {
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    dateOfBirth: "2000-05-15",
    email: "john.doe@student.edu",
    phone: "+855-12-345-6789",
    nationality: "Cambodian",
    address: "123 University Street, Phnom Penh, Cambodia",
  },
  academicInfo: {
    department: "Computer Science",
    major: "Software Engineering",
    class: "SE-2024-A",
    year: "4",
    advisor: "Dr. Sarah Johnson",
  },
};

export const mockStudentAttendance = [
  {
    id: "att_1",
    student: mockUsers[0], // Using first user as student
    studentId: "stu_1",
    schedule: mockStudentSchedule[0],
    scheduleId: "sch_1",
    date: "2025-10-25",
    status: "present",
    note: "",
    createdAt: "2025-10-25T08:30:00Z",
  },
  {
    id: "att_2",
    student: mockUsers[0],
    studentId: "stu_1",
    schedule: mockStudentSchedule[1],
    scheduleId: "sch_2",
    date: "2025-10-24",
    status: "late",
    note: "Traffic delay",
    createdAt: "2025-10-24T14:15:00Z",
  },
  {
    id: "att_3",
    student: mockUsers[0],
    studentId: "stu_1",
    schedule: mockStudentSchedule[2],
    scheduleId: "sch_3",
    date: "2025-10-23",
    status: "present",
    note: "",
    createdAt: "2025-10-23T10:30:00Z",
  },
  {
    id: "att_4",
    student: mockUsers[0],
    studentId: "stu_1",
    schedule: mockStudentSchedule[0],
    scheduleId: "sch_1",
    date: "2025-10-18",
    status: "absent",
    note: "Medical leave",
    createdAt: "2025-10-18T09:00:00Z",
  },
  {
    id: "att_5",
    student: mockUsers[0],
    studentId: "stu_1",
    schedule: mockStudentSchedule[1],
    scheduleId: "sch_2",
    date: "2025-10-17",
    status: "present",
    note: "",
    createdAt: "2025-10-17T14:30:00Z",
  },
];
