# Generated by Django 5.2.7 on 2025-11-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('application_review', 'Application Review'), ('student_creation', 'Student Creation'), ('schedule_creation', 'Schedule Creation'), ('attendance_monitor', 'Attendance Monitor'), ('report_generation', 'Report Generation')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Activity',
                'verbose_name_plural': 'Staff Activities',
            },
        ),
    ]
