# Generated by Django 5.2.7 on 2025-11-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='majors',
        ),
        migrations.AddField(
            model_name='subject',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.major'),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_for', to='admins.subject'),
        ),
    ]
