# Generated by Django 5.2.7 on 2025-11-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_remove_subject_majors_subject_major_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='schedule_day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='admins.major'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year_level',
            field=models.IntegerField(default=1),
        ),
    ]
